import { createObjectCsvWriter } from 'csv-writer';
import PDFDocument from 'pdfkit';
import Papa from 'papaparse';
import fs from 'fs';
import path from 'path';
import { AppError } from '../middleware/errorHandler';

// PDF translations
const pdfTranslations = {
  en: {
    title: 'Year-End Inventory Report',
    year: 'Year',
    confirmedLocked: 'CONFIRMED & LOCKED',
    draft: 'DRAFT',
    confirmed: 'Confirmed',
    generated: 'Generated',
    executiveSummary: 'Executive Summary',
    totalProducts: 'Total Products',
    expectedQuantity: 'Expected Quantity',
    countedQuantity: 'Counted Quantity',
    totalVariance: 'Total Variance',
    totalInventoryValue: 'Total Inventory Value',
    varianceAnalysis: 'Variance Analysis',
    surplus: 'Surplus (counted > expected)',
    shortage: 'Shortage (counted < expected)',
    exactMatch: 'Exact match',
    products: 'products',
    topSurpluses: 'Top 5 Surpluses',
    topShortages: 'Top 5 Shortages',
    detailedProductInventory: 'Detailed Product Inventory',
    product: 'Product',
    expected: 'Expected',
    counted: 'Counted',
    variance: 'Variance',
    valueFIFO: 'Value (FIFO)',
    notCounted: 'Not counted',
    endOfReport: '— End of Year-End Inventory Report —',
    autoGenerated: 'This document is generated automatically from the inventory management system.',
    confirmedData: '✓ This report is based on confirmed and locked data.',
    draftWarning: '⚠ This is a draft report. Data may change until confirmed.',
    page: 'Page',
  },
  sv: {
    title: 'Årsbokslut Lagerrapport',
    year: 'År',
    confirmedLocked: 'BEKRÄFTAD & LÅST',
    draft: 'UTKAST',
    confirmed: 'Bekräftad',
    generated: 'Genererad',
    executiveSummary: 'Sammanfattning',
    totalProducts: 'Totalt antal produkter',
    expectedQuantity: 'Förväntat antal',
    countedQuantity: 'Räknat antal',
    totalVariance: 'Total avvikelse',
    totalInventoryValue: 'Totalt lagervärde',
    varianceAnalysis: 'Avvikelseanalys',
    surplus: 'Överskott (räknat > förväntat)',
    shortage: 'Brist (räknat < förväntat)',
    exactMatch: 'Exakt matchning',
    products: 'produkter',
    topSurpluses: 'Topp 5 överskott',
    topShortages: 'Topp 5 brister',
    detailedProductInventory: 'Detaljerad produktinventering',
    product: 'Produkt',
    expected: 'Förväntat',
    counted: 'Räknat',
    variance: 'Avvikelse',
    valueFIFO: 'Värde (FIFO)',
    notCounted: 'Ej räknad',
    endOfReport: '— Slut på årsbokslut lagerrapport —',
    autoGenerated: 'Detta dokument genereras automatiskt från lagerhanteringssystemet.',
    confirmedData: '✓ Denna rapport baseras på bekräftade och låsta data.',
    draftWarning: '⚠ Detta är en utkastrapport. Data kan ändras tills den bekräftas.',
    page: 'Sida',
  },
};

export const exportService = {
  /**
   * Export count sheet to CSV with empty Actual Count column
   */
  async exportCountSheetCSV(countSheet: any): Promise<string> {
    const csvPath = path.join(process.cwd(), 'tmp', `count-sheet-${countSheet.year}-${Date.now()}.csv`);
    
    // Ensure tmp directory exists
    const tmpDir = path.join(process.cwd(), 'tmp');
    if (!fs.existsSync(tmpDir)) {
      fs.mkdirSync(tmpDir, { recursive: true });
    }

    const csvWriter = createObjectCsvWriter({
      path: csvPath,
      header: [
        { id: 'productName', title: 'Product Name' },
        { id: 'supplier', title: 'Supplier' },
        { id: 'expectedQuantity', title: 'Expected Quantity' },
        { id: 'actualCount', title: 'Actual Count' },
        { id: 'notes', title: 'Notes' },
      ],
    });

    const records = countSheet.items.map((item: any) => {
      // Get supplier names - show all suppliers separated by comma
      let supplierName = 'Unknown';
      if (item.product.suppliers && item.product.suppliers.length > 0) {
        supplierName = item.product.suppliers
          .map((ps: any) => ps.supplier.name)
          .join(', ');
      }

      return {
        productName: item.product.name,
        supplier: supplierName,
        expectedQuantity: item.expectedQuantity,
        actualCount: '', // Empty for user to fill
        notes: '',
      };
    });

    await csvWriter.writeRecords(records);
    return csvPath;
  },

  /**
   * Export count sheet to PDF for printing
   */
  async exportCountSheetPDF(countSheet: any): Promise<string> {
    const pdfPath = path.join(process.cwd(), 'tmp', `count-sheet-${countSheet.year}-${Date.now()}.pdf`);
    
    // Ensure tmp directory exists
    const tmpDir = path.join(process.cwd(), 'tmp');
    if (!fs.existsSync(tmpDir)) {
      fs.mkdirSync(tmpDir, { recursive: true });
    }

    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 50 });
      const stream = fs.createWriteStream(pdfPath);

      doc.pipe(stream);

      // Header
      doc
        .fontSize(20)
        .text(`Year-End Inventory Count - ${countSheet.year}`, { align: 'center' })
        .moveDown();

      // Format date as YYYY-MM-DD
      const today = new Date();
      const dateStr = `${today.getFullYear()}-${String(today.getMonth() + 1).padStart(2, '0')}-${String(today.getDate()).padStart(2, '0')}`;
      
      doc
        .fontSize(12)
        .text(`Date: ${dateStr}`, { align: 'center' })
        .text(`Total Products: ${countSheet.items.length}`, { align: 'center' })
        .moveDown(2);

      // Table header
      const tableTop = doc.y;
      const colWidths = {
        productName: 180,
        supplier: 160,
        expected: 70,
        actual: 70,
      };

      doc.fontSize(10).font('Helvetica-Bold');
      let x = 50;
      doc.text('Product Name', x, tableTop, { width: colWidths.productName });
      x += colWidths.productName;
      doc.text('Supplier', x, tableTop, { width: colWidths.supplier });
      x += colWidths.supplier;
      doc.text('Expected', x, tableTop, { width: colWidths.expected });
      x += colWidths.expected;
      doc.text('Actual', x, tableTop, { width: colWidths.actual });

      // Draw line under header
      doc
        .moveTo(50, tableTop + 15)
        .lineTo(530, tableTop + 15)
        .stroke();

      // Table rows
      doc.font('Helvetica').fontSize(8);
      let y = tableTop + 25;

      for (const item of countSheet.items) {
        // Get supplier names - show all suppliers separated by comma
        let supplierName = 'Unknown';
        if (item.product.suppliers && item.product.suppliers.length > 0) {
          supplierName = item.product.suppliers
            .map((ps: any) => ps.supplier.name)
            .join(', ');
        }

        // Calculate row height based on text height
        const productHeight = doc.heightOfString(item.product.name, { width: colWidths.productName });
        const supplierHeight = doc.heightOfString(supplierName, { width: colWidths.supplier });
        const rowHeight = Math.max(productHeight, supplierHeight, 20) + 5;

        // Check if we need a new page
        if (y + rowHeight > 720) {
          doc.addPage();
          y = 50;
        }

        x = 50;
        doc.text(item.product.name, x, y, { width: colWidths.productName, lineBreak: true });
        x += colWidths.productName;
        doc.text(supplierName, x, y, { width: colWidths.supplier, lineBreak: true });
        x += colWidths.supplier;
        doc.text(item.expectedQuantity.toString(), x, y, { width: colWidths.expected });
        x += colWidths.expected;
        // Show counted quantity if available, otherwise blank line for manual entry
        const actualText = item.countedQuantity !== null && item.countedQuantity !== undefined
          ? item.countedQuantity.toString()
          : '_________';
        doc.text(actualText, x, y, { width: colWidths.actual });

        y += rowHeight;
      }

      // Footer
      doc
        .moveDown(3)
        .fontSize(10)
        .text('Instructions: Count each product physically and write the actual quantity above.', 50)
        .moveDown()
        .text(`Counted by: ________________________  Date: ________________`, 50);

      doc.end();

      stream.on('finish', () => resolve(pdfPath));
      stream.on('error', reject);
    });
  },

  /**
   * Import count data from CSV
   */
  async importCountDataCSV(csvContent: string): Promise<any[]> {
    return new Promise((resolve, reject) => {
      Papa.parse(csvContent, {
        header: true,
        skipEmptyLines: true,
        complete: (results) => {
          // Validate and transform data
          const validatedData: any[] = [];
          const errors: string[] = [];

          results.data.forEach((row: any, index: number) => {
            const rowNum = index + 2; // +2 for header and 0-based index

            // Validate required fields
            if (!row['Product Name'] || row['Product Name'].trim() === '') {
              errors.push(`Row ${rowNum}: Product Name is required`);
              return;
            }

            if (!row['Actual Count'] || row['Actual Count'].trim() === '') {
              errors.push(`Row ${rowNum}: Actual Count is required`);
              return;
            }

            // Validate actual count is a number
            const actualCount = parseInt(row['Actual Count']);
            if (isNaN(actualCount) || actualCount < 0) {
              errors.push(`Row ${rowNum}: Actual Count must be a non-negative number`);
              return;
            }

            validatedData.push({
              productName: row['Product Name'].trim(),
              actualCount,
            });
          });

          if (errors.length > 0) {
            reject(new AppError(400, `CSV validation errors:\n${errors.join('\n')}`));
          } else {
            resolve(validatedData);
          }
        },
        error: (error: any) => {
          reject(new AppError(400, `CSV parsing error: ${error.message}`));
        },
      });
    });
  },

  /**
   * Export comprehensive year-end count report to PDF for bookkeeping
   * Includes summary, variance analysis, product details, and lot breakdown
   * @param reportData - The year-end count report data
   * @param language - Language for the report ('en' or 'sv'), defaults to 'en'
   */
  async exportYearEndReportPDF(reportData: any, language: string = 'en'): Promise<string> {
    const pdfPath = path.join(
      process.cwd(),
      'tmp',
      `year-end-report-${reportData.year}-${Date.now()}.pdf`
    );

    // Ensure tmp directory exists
    const tmpDir = path.join(process.cwd(), 'tmp');
    if (!fs.existsSync(tmpDir)) {
      fs.mkdirSync(tmpDir, { recursive: true });
    }

    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const stream = fs.createWriteStream(pdfPath);

      doc.pipe(stream);

      // Get translations for selected language
      const lang = language === 'sv' ? 'sv' : 'en';
      const t = pdfTranslations[lang];

      // Helper function to format currency
      const formatCurrency = (value: number) => {
        const locale = lang === 'sv' ? 'sv-SE' : 'en-US';
        const currency = lang === 'sv' ? 'SEK' : 'USD';
        const formatted = new Intl.NumberFormat(locale, {
          style: 'currency',
          currency: currency,
          minimumFractionDigits: 2,
        }).format(value);
        // Replace non-breaking spaces and Unicode minus signs with regular characters for PDF compatibility
        return formatted
          .replace(/\u00A0/g, ' ')      // Non-breaking space -> regular space
          .replace(/\u2212/g, '-')      // Unicode minus sign -> hyphen-minus
          .replace(/\u2013/g, '-')      // En dash -> hyphen-minus
          .replace(/\u2014/g, '-');     // Em dash -> hyphen-minus
      };

      // Helper function to format number with 2 decimals
      const formatNumber = (value: number) => {
        const locale = lang === 'sv' ? 'sv-SE' : 'en-US';
        const formatted = new Intl.NumberFormat(locale, {
          minimumFractionDigits: 2,
          maximumFractionDigits: 2,
        }).format(value);
        // Replace non-breaking spaces and Unicode minus signs with regular characters for PDF compatibility
        return formatted
          .replace(/\u00A0/g, ' ')      // Non-breaking space -> regular space
          .replace(/\u2212/g, '-')      // Unicode minus sign -> hyphen-minus
          .replace(/\u2013/g, '-')      // En dash -> hyphen-minus
          .replace(/\u2014/g, '-');     // Em dash -> hyphen-minus
      };

      // Helper to add page header
      const addPageHeader = (pageNum: number) => {
        doc
          .fontSize(8)
          .fillColor('#666')
          .text(`${t.title} - ${reportData.year}`, 50, 30, { align: 'left' })
          .text(`${t.page} ${pageNum}`, 50, 30, { align: 'right' })
          .fillColor('#000');
      };

      let pageNum = 1;

      // ============================================================
      // PAGE 1: EXECUTIVE SUMMARY
      // ============================================================
      
      // Title
      doc
        .fontSize(24)
        .font('Helvetica-Bold')
        .text(t.title, { align: 'center' })
        .moveDown(0.5);

      doc
        .fontSize(18)
        .text(`${t.year} ${reportData.year}`, { align: 'center' })
        .moveDown(0.3);

      // Status badge
      const statusText = reportData.status === 'confirmed' ? t.confirmedLocked : t.draft;
      const statusColor = reportData.status === 'confirmed' ? '#28a745' : '#ffc107';
      doc
        .fontSize(12)
        .fillColor(statusColor)
        .text(statusText, { align: 'center' })
        .fillColor('#000')
        .moveDown(0.3);

      // Date
      if (reportData.confirmedAt) {
        const confirmedDate = new Date(reportData.confirmedAt);
        const locale = lang === 'sv' ? 'sv-SE' : 'en-US';
        doc
          .fontSize(10)
          .fillColor('#666')
          .text(`${t.confirmed}: ${confirmedDate.toLocaleDateString(locale)}`, { align: 'center' })
          .fillColor('#000');
      }

      const generatedDate = new Date();
      const locale = lang === 'sv' ? 'sv-SE' : 'en-US';
      doc
        .fontSize(10)
        .fillColor('#666')
        .text(`${t.generated}: ${generatedDate.toLocaleDateString(locale)}`, { align: 'center' })
        .fillColor('#000')
        .moveDown(2);

      // Summary Box
      doc
        .fontSize(14)
        .font('Helvetica-Bold')
        .text(t.executiveSummary, 50)
        .moveDown(0.5);

      // Draw summary box
      const summaryBoxY = doc.y;
      doc
        .rect(50, summaryBoxY, 495, 120)
        .fillAndStroke('#f8f9fa', '#dee2e6');

      // Summary content
      doc.fillColor('#000');
      let summaryY = summaryBoxY + 15;
      const leftCol = 70;
      const rightCol = 320;

      doc
        .fontSize(11)
        .font('Helvetica-Bold')
        .text(`${t.totalProducts}:`, leftCol, summaryY)
        .font('Helvetica')
        .text(reportData.items.length.toString(), leftCol + 150, summaryY);

      summaryY += 25;
      doc
        .font('Helvetica-Bold')
        .text(`${t.expectedQuantity}:`, leftCol, summaryY)
        .font('Helvetica')
        .text(formatNumber(reportData.totalExpected), leftCol + 150, summaryY);

      doc
        .font('Helvetica-Bold')
        .text(`${t.countedQuantity}:`, rightCol, summaryY)
        .font('Helvetica')
        .text(formatNumber(reportData.totalCounted), rightCol + 150, summaryY);

      summaryY += 25;
      const varianceColor = reportData.totalVariance >= 0 ? '#28a745' : '#dc3545';
      doc
        .font('Helvetica-Bold')
        .text(`${t.totalVariance}:`, leftCol, summaryY)
        .font('Helvetica')
        .fillColor(varianceColor)
        .text(
          `${reportData.totalVariance >= 0 ? '+' : ''}${formatNumber(reportData.totalVariance)}`,
          leftCol + 150,
          summaryY
        )
        .fillColor('#000');

      doc
        .font('Helvetica-Bold')
        .text(`${t.totalInventoryValue}:`, rightCol, summaryY)
        .font('Helvetica')
        .fillColor('#0066cc')
        .fontSize(12)
        .text(formatCurrency(reportData.totalValue), rightCol + 150, summaryY)
        .fillColor('#000')
        .fontSize(11);

      // ============================================================
      // PAGE 2+: DETAILED PRODUCT LIST
      // ============================================================
      
      doc.addPage();
      pageNum++;
      addPageHeader(pageNum);

      doc.y = 50;
      doc
        .fontSize(16)
        .font('Helvetica-Bold')
        .text(t.detailedProductInventory, 50)
        .moveDown(1);

      // Table header
      const tableTop = doc.y;
      doc.fontSize(9).font('Helvetica-Bold');
      
      const cols = {
        product: { x: 50, width: 140 },
        expected: { x: 195, width: 55 },
        counted: { x: 255, width: 55 },
        variance: { x: 315, width: 60 },
        value: { x: 380, width: 75 },
      };

      doc.text(t.product, cols.product.x, tableTop, { width: cols.product.width });
      doc.text(t.expected, cols.expected.x, tableTop, { width: cols.expected.width, align: 'right' });
      doc.text(t.counted, cols.counted.x, tableTop, { width: cols.counted.width, align: 'right' });
      doc.text(t.variance, cols.variance.x, tableTop, { width: cols.variance.width, align: 'right' });
      doc.text(t.valueFIFO, cols.value.x, tableTop, { width: cols.value.width, align: 'right' });

      // Draw line under header
      doc
        .moveTo(50, tableTop + 12)
        .lineTo(545, tableTop + 12)
        .stroke();

      // Table rows
      doc.font('Helvetica').fontSize(8);
      let y = tableTop + 20;

      // Sort items by product name
      const sortedItems = reportData.items.sort((a: any, b: any) =>
        a.productName.localeCompare(b.productName)
      );

      for (const item of sortedItems) {
        // Check if we need a new page
        if (y > 750) {
          doc.addPage();
          pageNum++;
          addPageHeader(pageNum);
          y = 70;
          
          // Redraw table header
          doc.fontSize(9).font('Helvetica-Bold');
          doc.text(t.product, cols.product.x, y - 15, { width: cols.product.width });
          doc.text(t.expected, cols.expected.x, y - 15, { width: cols.expected.width, align: 'right' });
          doc.text(t.counted, cols.counted.x, y - 15, { width: cols.counted.width, align: 'right' });
          doc.text(t.variance, cols.variance.x, y - 15, { width: cols.variance.width, align: 'right' });
          doc.text(t.valueFIFO, cols.value.x, y - 15, { width: cols.value.width, align: 'right' });
          
          doc
            .moveTo(50, y - 3)
            .lineTo(545, y - 3)
            .stroke();
            
          doc.font('Helvetica').fontSize(8);
        }

        // Product name with supplier
        const productText = item.supplierName
          ? `${item.productName}\n(${item.supplierName})`
          : item.productName;
        
        const rowHeight = Math.max(
          doc.heightOfString(productText, { width: cols.product.width }),
          20
        );

        doc.text(productText, cols.product.x, y, { width: cols.product.width });
        doc.text(formatNumber(item.expectedQuantity), cols.expected.x, y, {
          width: cols.expected.width,
          align: 'right',
        });

        if (item.countedQuantity !== null) {
          doc.text(formatNumber(item.countedQuantity), cols.counted.x, y, {
            width: cols.counted.width,
            align: 'right',
          });

          if (item.variance !== null) {
            const varianceColor = item.variance >= 0 ? '#28a745' : '#dc3545';
            doc.fillColor(varianceColor);
            doc.text(
              `${item.variance >= 0 ? '+' : ''}${formatNumber(item.variance)}`,
              cols.variance.x,
              y,
              { width: cols.variance.width, align: 'right' }
            );
            doc.fillColor('#000');
          }

          if (item.value !== null) {
            doc.fillColor('#0066cc');
            doc.text(formatCurrency(item.value), cols.value.x, y, {
              width: cols.value.width,
              align: 'right',
            });
            doc.fillColor('#000');
          }
        } else {
          doc.fillColor('#999');
          doc.text(t.notCounted, cols.counted.x, y, { width: 150 });
          doc.fillColor('#000');
        }

        y += rowHeight + 3;

        // Draw separator line
        doc
          .strokeColor('#e9ecef')
          .moveTo(50, y)
          .lineTo(545, y)
          .stroke()
          .strokeColor('#000');

        y += 2;
      }

      // ============================================================
      // FOOTER ON LAST PAGE
      // ============================================================

      doc.moveDown(2);
      doc
        .fontSize(9)
        .fillColor('#666')
        .text(
          t.endOfReport,
          { align: 'center' }
        )
        .moveDown(0.5)
        .fontSize(8)
        .text(
          t.autoGenerated,
          { align: 'center' }
        );

      if (reportData.status === 'confirmed') {
        doc
          .fillColor('#28a745')
          .text(
            t.confirmedData,
            { align: 'center' }
          );
      } else {
        doc
          .fillColor('#ffc107')
          .text(
            t.draftWarning,
            { align: 'center' }
          );
      }

      doc.end();

      stream.on('finish', () => resolve(pdfPath));
      stream.on('error', reject);
    });
  },

  /**
   * Clean up temporary files
   */
  cleanupTempFile(filePath: string) {
    try {
      if (fs.existsSync(filePath)) {
        fs.unlinkSync(filePath);
      }
    } catch (error) {
      console.error('Error cleaning up temp file:', error);
    }
  },

  /**
   * Clean up old temporary files (files older than 1 hour)
   * Should be called periodically to prevent disk space issues
   */
  cleanupOldTempFiles() {
    try {
      const tmpDir = path.join(process.cwd(), 'tmp');
      
      // Create tmp directory if it doesn't exist
      if (!fs.existsSync(tmpDir)) {
        fs.mkdirSync(tmpDir, { recursive: true });
        return;
      }

      const files = fs.readdirSync(tmpDir);
      const now = Date.now();
      const ONE_HOUR = 60 * 60 * 1000;
      let deletedCount = 0;

      for (const file of files) {
        const filePath = path.join(tmpDir, file);
        const stats = fs.statSync(filePath);

        // Delete files older than 1 hour
        if (now - stats.mtimeMs > ONE_HOUR) {
          fs.unlinkSync(filePath);
          deletedCount++;
        }
      }

      if (deletedCount > 0) {
        console.log(`Cleaned up ${deletedCount} old temporary file(s)`);
      }
    } catch (error) {
      console.error('Error cleaning up old temp files:', error);
    }
  },
};
